name: Test Action
on:
  push:
    branches:
      - main

jobs:
  check-validation:
    runs-on: ubuntu-latest
    name: Check commit signing
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check commit
        uses: ./
        id: check-commit
      - name: Show check-commit
        run: echo "${{ steps.check-commit.outputs.commit }}"
